### ISSUE TITLE
Add an utility to matierialize a Mirror inside macro

### ISSUE THREAD

**Issue by chuwy** [kitlangton/quotidian#3]
[Raised this](https://github.com/typelevel/shapeless-3/issues/133) recently in shapeless-3, but maybe indeed the purpose of shapeless is to provide a more generic type-level programming capabilities (not necessarily macro-oriented), whereas this project  seems to cover exactly that need of small useful macro utilities. Anyways, I'd be happy to see the macro-mirror _somewhere_.

**Comment by kitlangton** [comment]
That's a great idea! I was thinking of adding something quite similar to that, though perhaps outfitted with even more fields/methods that the usual mirror. But yes, some kind of macro-mirror is in order! (Actually, the difficulty I was having was with the name—but `MacroMirror` alliterates very nicely!)

**Comment by kitlangton** [comment]
Okay @chuwy! I added a `MacroMirror` that does similar things! Let me know if you want more.

**Comment by chuwy** [comment]
That looks flawless to me. Can't wait to try it out. Thank you very much, @kitlangton!

**Comment by kitlangton** [comment]
@chuwy Heads up! I changed it to return an `Option`, so it's more like `Expo.summon`.
