### ISSUE TITLE
Broken release at maven central

### ISSUE THREAD

**Issue by danslapman** [kitlangton/quotidian#6]
Hello @kitlangton! Thank you very much for this toolbox! Unfortunately the last published release (0.0.10) in maven central is broken (it seems it is an empty jar) an 0.0.7-0.0.9 are absent :( could you please publish fixed version? Thanks!

**Comment by kitlangton** [comment]
😅 Oopsies!

Thanks for letting me know. I've just tried to fix the build.  Let me know if `0.0.12` works for ya (once the pipeline completes in just a few minutes).

**Comment by danslapman** [comment]
Thanks @kitlangton, but 0.0.11 seems to be broken as well 😔

**Comment by danslapman** [comment]
Regarding documentation - for a person somehow familiar with macros quotidian is pretty intuitive, it's a definitive sign of great work 👍 But truly, examples are helpful - my current desire is to implement companion-object-based derivation for https://github.com/tofu-tf/glass

**Comment by kitlangton** [comment]
No idea what was wrong, but version `0.0.14` seems to be working. I checked this time in another local project :D.

**Comment by danslapman** [comment]
0.0.14 is fine, thanks!

**Comment by kitlangton** [comment]
You're very welcome! Good luck with your macros ;)
